# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2c067216d4d0db7f6127f90445645a7a0d638c1aa2e13b1873adb0ccd8c5f95e5ae5e41c90371a1d93691291acd75d376dd439c9459ce9da42446b6f17677aa

test:
  secret_key_base: e1ad7750d722396bf1d5a58bc1f10c6b072ee4bf4a91553f1595613d74458295ea9722c6e96b3740cc1287047931edb717d4fe383f12e928ec5c8de1db48a526

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
